#!/bin/sh

# Example for $XDG_CONFIG_HOME/sxiv/exec/key-handler
# Called by sxiv(1) after the external prefix key (C-x by default) is pressed.
# The next key combo is passed as its first argument. Passed via stdin are the
# images to act upon, one path per line: all marked images, if in thumbnail
# mode and at least one image has been marked, otherwise the current image.
# sxiv(1) blocks until this script terminates. It then checks which images
# have been modified and reloads them.

# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the X
# keysym as listed in /usr/include/X11/keysymdef.h without the "XK_" prefix.
#@set_wallpaper
#+ Set Wallpaper using feh or nitrogen
#
# How we set wallpaper is copy it to config dir as wall.png
# Then pass it to feh for setting as desktop background
# If user has not installed feh then use nitrogen
set_wallpaper(){
    if [ -f /usr/bin/feh ]; then
        cp "$1" ~/.config/wall.png
        # ln -sf "$1" ~/.config/wall.png
        feh --bg-fill --no-fehbg ~/.config/wall.png
        notify-send "Wallpaper Updated" "$1"
        exit 0
    fi
    if [ -f /usr/bin/nitrogen ]; then
        nitrogen --save --set-scaled "$1"
        notify-send "Wallpaper Set using Nitrogen" "$1"
        exit 0
    fi

    notify-send -u critical "Software Not installed" "Please install feh or nitrogen for this to work"
}

while read -r file; do
    case "$1" in
    "C") printf "%s\n" "$file" | tr -d '\n' | xclip -selection clipboard &&
        notify-send "$file copied to clipboard" & ;;
    "c") xclip -selection clipboard -target image/png "$file" &&
        notify-send "$file copied to clipboard" & ;;
    "w") set_wallpaper "$file" &;;
    "r") convert -rotate 90 "$file" "$file" ;;
    "R") convert -rotate 180 "$file" "$file" ;;
    esac
done
