version: "2"

linters:
  enable:
    - gocyclo
    - gocognit
  settings:
    gocyclo:
      min-complexity: 10
    gocognit:
      min-complexity: 15
  exclusions:
    presets: []

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false
