# vim:filetype=hyprlang

$lock_cmd = pidof hyprlock || hyprlock
$suspend_cmd = systemctl suspend || loginctl suspend
$dpms_off = niri msg action power-off-monitors
$dpms_on = niri msg action power-on-monitors

general {
  lock_cmd = $lock_cmd
  before_sleep_cmd = loginctl lock-session    # Automatically lock before any suspend/sleep event.
  after_sleep_cmd = $dpms_off # Turn screens back on after resuming from sleep.
  inhibit_sleep = 3
}

# Optional: Dim screen brightness before locking (e.g., after 2.5 minutes).
listener {
  timeout = 150
  on-timeout = brightnessctl -s set 5        # Dim monitor to 5% (requires brightnessctl package).
  on-resume = brightnessctl -r                # Restore brightness on activity.
}

# Lock the screen after 5 minutes of inactivity.
listener {
  timeout = 300
  on-timeout = loginctl lock-session
  on-resume = $dpms_on
}

# Optional: Turn off screens (DPMS) shortly after locking to save power.
listener {
  timeout = 360
  on-timeout = $dpms_off
  on-resume = $dpms_on
}

# Suspend after total 15 minutes of inactivity (i.e., 10 minutes after lock, if inactivity continues).
listener {
  timeout = 600
  on-timeout = $suspend_cmd
}
