#!/bin/sh

userresources=$HOME/.config/X11/Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# run() {
# 	if ! pgrep $1; then
# 		$@ &
# 	fi
# }

source ~/.config/X11/profile

# bash ~/.local/bin/myscripts/default_mouse_settings &
# /usr/bin/setxkbmap -option "caps:swapescape"
# setsid -f kmonad ~/.config/kmonad/mkmonad.kbd
# xset -b
# xsetroot -cursor_name left_ptr
# 
# run xcompmgr -c -C -t-5 -l-5 -r4.2 -o.6
# run picom --experimental-backends
# run dunst
# run feh --no-fehbg --bg-fill ~/.config/wall.png
# run kitty
# # run alacritty -e "tmux"
# run redshift
# run greenclip daemon
# run imwheel
exec bspwm
