#!/bin/bash
run() {
  if ! pgrep "$1"; then
    if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
      XDG_CURRENT_DESKTOP=Unity $@ &
    else
      $@ &
    fi
  fi
}

setsid -f kmonad ~/.config/kmonad/mkmonad.kbd
if [ "$XDG_SESSION_TYPE" != "wayland" ]; then
  bash ~/.local/bin/myscripts/default_mouse_settings &
  # setxkbmap -option 'ctrl:nocaps' -option 'shift:both_capslock'
  # xcape -e 'Control_L=Escape'
  numlockx on
  xset -b
  xsetroot -cursor_name left_ptr
fi

basic() {
  # bash ~/.local/bin/myscripts/if_void &
  # run lxpolkit
  # run /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1
  run /usr/lib/polkit-kde-authentication-agent-1
  # run dunst
  if [ "$XDG_SESSION_TYPE" != "wayland" ]; then
    # run xcompmgr -c -C -t-5 -l-5 -r4.2 -o.8
    run picom -b #--experimental-backends
    run xwallpaper --stretch ~/.config/wall.png
    # run feh --bg-fill --no-fehbg -q ~/.config/wall.png
  fi
  run kitty
  # run alacritty -e "tmux"
  run udiskie -q -t --no-terminal
}

case "$DESKTOP_SESSION" in
  bspwm | awesome | qtile | dk)
    basic
    xset -b
    ;;
  dwm)
    basic
    run dwmblocks
    run sxhkd -c ~/.config/sxhkd/dwm_sxhkdrc
    ;;
esac

run redshift -m randr -l manual -l '18.520430:73.856743' -g 0.8 -b '0.9:0.7'
run nm-applet
run greenclip daemon
run flameshot
run imwheel
