require("mini.clue").setup({
	triggers = {
		{ mode = "c", keys = "<C-r>" },
		{ mode = "i", keys = "<C-r>" },
		{ mode = "i", keys = "<C-x>" },
		{ mode = "n", keys = "'" },
		{ mode = "n", keys = "<C-w>" },
		{ mode = "n", keys = "<leader>" },
		{ mode = "n", keys = "[" },
		{ mode = "n", keys = "\\" },
		{ mode = "n", keys = "]" },
		{ mode = "n", keys = "`" },
		{ mode = "n", keys = "g" },
		{ mode = "n", keys = "z" },
		{ mode = "n", keys = '"' },
		{ mode = "x", keys = "'" },
		{ mode = "x", keys = "<leader>" },
		{ mode = "x", keys = "[" },
		{ mode = "x", keys = "]" },
		{ mode = "x", keys = "`" },
		{ mode = "x", keys = "g" },
		{ mode = "x", keys = "z" },
		{ mode = "x", keys = '"' },
	},
	clues = {
		{
			{ mode = "n", keys = "<leader>b", desc = "+Buffer" },
			{ mode = "n", keys = "<leader>c", desc = "+Code" },
			{ mode = "n", keys = "<leader>e", desc = "+Explorer" },
			{ mode = "n", keys = "<leader>f", desc = "+Find" },
			{ mode = "n", keys = "<leader>g", desc = "+Git" },
			{ mode = "n", keys = "<leader>l", desc = "+Lsp" },
			{ mode = "n", keys = "<leader>m", desc = "+MultiCursors" },
			{ mode = "n", keys = "<leader>q", desc = "+Session" },
			-- { mode = "n", keys = "<leader>x", desc = "+QuickFix" },
			{ mode = "n", keys = "<leader>o", desc = "+Open" },
			{ mode = "n", keys = "<leader>v", desc = "+Visits" },
		},
		require("mini.clue").gen_clues.builtin_completion(),
		require("mini.clue").gen_clues.g(),
		require("mini.clue").gen_clues.marks(),
		require("mini.clue").gen_clues.registers(),
		require("mini.clue").gen_clues.square_brackets(),
		require("mini.clue").gen_clues.windows(),
		require("mini.clue").gen_clues.z(),
	},
	window = { delay = 0 },
})
