# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
gui:
  nerdFontsVersion: "3"
  scrollHeight: 2
  scrollPastBottom: true
  mouseEvents: true
  border: rounded
git:
  merging:
    manualCommit: true
  pagers:
    - pager: delta --dark --paging=never --line-numbers --hyperlinks
        --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
    - colorArg: always

os:
  editPreset: nvim
