name: xmonad-vem
version: 0.1

ghc-options: -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints -O2 -j -dynamic

dependencies:
  - base
  - containers
  - directory
  - filepath
  - process
  - regex-tdfa
  - utf8-string
  - unix
  - dbus
  - xmonad >= 0.17
  - xmonad-contrib >= 0.17

executables:
  xmonad:
    main: xmonad.hs
    dependencies:
      - xmonad
      - X11 >= 1.10
