#!/bin/sh

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"

#LAUNCHERS
bash ~/.config/bspwm/autostart.sh

bspc config border_width                2
bspc config window_gap                  3

bspc config top_padding                 23
bspc config bottom_padding              -1
bspc config left_padding                -1
bspc config right_padding               -1
bspc config left_monocle_padding        2
bspc config right_monocle_padding       1
bspc config bottom_monocle_padding      2

bspc config single_monocle              true
bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_follows_pointer       true

bspc config pointer_modifier            mod4
bspc config pointer_action1             move
bspc config pointer_action2             resize_side
bspc config pointer_action3             resize_corner
bspc config remove_disabled_monitors    true
bspc config merge_overlapping_monitors  true

#BSPWM coloring
bspc config normal_border_color         "#4c566a"
bspc config active_border_color         "#1e1e1e"
# bspc config focused_border_color        "#fba922"
bspc config focused_border_color        "#bd93f9"
bspc config presel_feedback_color       "#5e81ac"

#Single monitor
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

#Dual monitor
#find out names with arandr or xrandr
#bspc monitor HDMI1 -d 1 2 3 4 5
#bspc monitor HDMI2 -d 6 7 8 9 10

#Fullscreen applications
bspc rule -a Vlc state=fullscreen

#Floating applications
bspc rule -a Arandr                     state=floating
bspc rule -a Arcolinux-tweak-tool.py    state=floating
bspc rule -a Arcolinux-welcome-app.py   state=floating
bspc rule -a Connman-gtk                state=floating
bspc rule -a Arcologout.py              state=fullscreen

bspc rule -a albert                     state=floating  focus=true
bspc rule -a feh                        state=floating
bspc rule -a Galculator                 state=floating
bspc rule -a Qalculate-gtk              state=floating
bspc rule -a Gnome-calculator           state=floating

bspc rule -a Nitrogen                   state=floating
bspc rule -a Oblogout                   state=floating
bspc rule -a NoiseTorch                 state=floating

bspc rule -a "Grub-customizer"          state=floating
bspc rule -a Pavucontrol                state=floating
bspc rule -a rofi                       state=floating
bspc rule -a matplotlib                 state=floating
#Tiled applications
bspc rule -a Gnome-disks                state=tiled
bspc rule -a Xfce4-settings-manager     state=tiled

bspc rule -a Emacs state=tiled
bspc rule -a Surf  state=tiled
bspc rule -a Zathura state=tiled

bspc rule -a firefox                    desktop='^2' follow=on
bspc rule -a Firefox                    desktop='^2' follow=on
bspc rule -a Nyxt                       desktop='^2' follow=on
bspc rule -a LibreWolf                  desktop='^2' follow=on
bspc rule -a Chromium                   desktop='^2' follow=on
bspc rule -a Chromium-browser           desktop='^2' follow=on
bspc rule -a waterfox-current           desktop='^2' follow=on
bspc rule -a Brave-browser              desktop='^2' follow=on
bspc rule -a qutebrowser                desktop='^2' follow=on

bspc rule -a Steam                      state=floating  desktop='^3'
bspc rule -a Lutris                     state=floating  desktop='^3'
bspc rule -a "Timeshift-gtk"            state=floating  desktop='^3' follow=on

bspc rule -a mpv                        desktop='^4' follow=on
bspc rule -a Evolution                  desktop="^4" follow=on
bspc rule -a Evolution-alarm-notify     state=floating

bspc rule -a "VirtualBox Manager"       state=floating  desktop='^5' follow=on
bspc rule -a Virt-manager               state=floating  desktop='^5' follow=on

bspc rule -a "VirtualBox Machine"       state=floating  desktop='^6' follow=on
