#!/bin/bash

output="$(brightnessctl g)"
light="${output/.*/}"

[ $? -ne 0 ] && exit $?

if [ "$light" -gt 90 ]; then
  icon=" "
elif [ "$light" -gt 70 ]; then
  icon=" "
elif [ "$light" -gt 50 ]; then
  icon=" "
elif [ "$light" -gt 40 ]; then
  icon=" "
elif [ "$light" -gt 10 ]; then
  icon=" "
else
  icon=" "
fi

echo "$icon  $light%"
