#!/bin/sh

case $BLOCK_BUTTON in
	1) setsid -f "$TERMINAL" -e pulsemixer ;;
	2) pactl set-sink-mute @DEFAULT_SINK@ toggle ;;
	4) pactl set-sink-volume @DEFAULT_SINK@ +5% ;;
	5) pactl set-sink-volume @DEFAULT_SINK@ -5% ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

if pactl get-sink-mute @DEFAULT_SINK@ | grep yes > /dev/null; then
	echo "婢 Muted"
	exit
fi

vol="$(pactl get-sink-volume @DEFAULT_SINK@ | awk -F ' / ' '{print $2}' | tr -cd '[:digit:]')"
[ $? -ne 0 ] && exit $?

if [ "$vol" -gt 70 ]; then
	icon=" "
elif [ "$vol" -gt 40 ]; then
	icon="墳 "
elif [ "$vol" -gt 10 ]; then
	icon=" "
else
	icon="奄 "
fi

echo "$icon $vol%"
