live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[[colors.indexed_colors]]
color = "0xff9e64"
index = 16

[[colors.indexed_colors]]
color = "0xdb4b4b"
index = 17

[colors.bright]
black = "0x414868"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xc0caf5"
yellow = "0xe0af68"

[colors.normal]
black = "0x15161e"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xa9b1d6"
yellow = "0xe0af68"

[colors.primary]
background = "#0f111a"
foreground = "0xc0caf5"

[cursor]
unfocused_hollow = true

[font]
size = 11.5

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
action = "Copy"
regex = "[a-zA-Z0-9+_.-]+@[a-zA-Z0-9.-]+"

[hints.enabled.binding]
key = "E"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SearchBackward"
key = "B"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mode = "~Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "Up"
mode = "~Alt"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "Down"
mode = "~Alt"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "Up"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "Down"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Equals"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "Space"
mode = "Vi"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Escape"
mods = "Alt"

[[keyboard.bindings]]
action = "ClearSelection"
key = "Escape"
mode = "Vi"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "I"
mode = "Vi"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "I"
mode = "Vi"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "G"
mode = "Vi"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "G"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "B"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "F"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "Open"
key = "U"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollHalfPageDown"
key = "D"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "Y"
mode = "Vi"

[[keyboard.bindings]]
action = "ToggleNormalSelection"
key = "V"
mode = "Vi"

[[keyboard.bindings]]
action = "ToggleLineSelection"
key = "V"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "ToggleBlockSelection"
key = "V"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleSemanticSelection"
key = "V"
mode = "Vi"
mods = "Alt"

[[keyboard.bindings]]
action = "Open"
key = "Return"
mode = "Vi"

[[keyboard.bindings]]
action = "Up"
key = "K"
mode = "Vi"

[[keyboard.bindings]]
action = "ScrollHalfPageUp"
key = "K"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "Down"
key = "J"
mode = "Vi"

[[keyboard.bindings]]
action = "ScrollHalfPageDown"
key = "J"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "Left"
key = "H"
mode = "Vi"

[[keyboard.bindings]]
action = "Right"
key = "L"
mode = "Vi"

[[keyboard.bindings]]
action = "Up"
key = "Up"
mode = "Vi"

[[keyboard.bindings]]
action = "Down"
key = "Down"
mode = "Vi"

[[keyboard.bindings]]
action = "Left"
key = "Left"
mode = "Vi"

[[keyboard.bindings]]
action = "Right"
key = "Right"
mode = "Vi"

[[keyboard.bindings]]
action = "FirstOccupied"
key = "Key0"
mode = "Vi"

[[keyboard.bindings]]
action = "Last"
key = "Key4"
mode = "Vi"

[[keyboard.bindings]]
action = "High"
key = "H"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "Middle"
key = "M"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "Low"
key = "L"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "SemanticLeft"
key = "B"
mode = "Vi"

[[keyboard.bindings]]
action = "SemanticRight"
key = "W"
mode = "Vi"

[[keyboard.bindings]]
action = "SemanticRightEnd"
key = "E"
mode = "Vi"

[[keyboard.bindings]]
action = "WordLeft"
key = "B"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "WordRight"
key = "W"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "WordRightEnd"
key = "E"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "SearchForward"
key = "Slash"
mode = "Vi"

[[keyboard.bindings]]
action = "SearchBackward"
key = "Slash"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "SearchNext"
key = "N"
mode = "Vi"

[[keyboard.bindings]]
action = "SearchPrevious"
key = "N"
mode = "Vi"
mods = "Shift"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[[mouse.bindings]]
action = "CopySelection"
mouse = "Left"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

# [shell]
# args = ["--login"]
# program = "/bin/fish"

[window]
opacity = 0.9
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"
