words = [
    "basedpyright",
    "bufnr",
    "catppuccin",
    "efm",
    "emmylua",
    "flavour",
    "keymap",
    "keymaps",
    "lazyvim",
    "macchiato",
    "navic",
    "neovim",
    "pyright",
    "undercurl",
    "vtsls",
]
