column_width = 120
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferDouble"
# sort_requires = true
call_parentheses = "NoSingleString"
collapse_simple_statement = "Always"
