return {
	n = {
		[",w"] = { "<cmd>w!<cr>", desc = "Save File" },
		[",W"] = { "<cmd>noautocmd w!<cr>", desc = "Save File(noautocmd)" },
		["<leader>c"] = false,
		["0"] = { "^" },
		["<Esc>"] = { "<cmd>nohl<cr>", desc = "No Highlight" },
		["dl"] = { '"_dl' },
		["c"] = { '"_c' },
		["C"] = { '"_C' },
		["Q"] = { "<cmd>copen<cr>", desc = "Open Quickfix list" },
		["]q"] = { "<cmd>cn<cr>", desc = "Quickfix Next " },
		["[q"] = { "<cmd>cprev<cr>", desc = "Quickfix Prev " },
		["<leader>v"] = { "v$", desc = "Select till end" },
		["<leader>1"] = { "1gt", desc = "Goto tab 1" },
		["<leader>2"] = { "2gt", desc = "Goto tab 2" },
		["<leader>3"] = { "3gt", desc = "Goto tab 3" },
		["<leader>4"] = { "4gt", desc = "Goto tab 4" },
		["<leader>5"] = { "5gt", desc = "Goto tab 5" },
		["<leader>6"] = { "6gt", desc = "Goto tab 6" },
		["<leader>7"] = { "7gt", desc = "Goto tab 7" },
		["<leader>8"] = { "8gt", desc = "Goto tab 8" },
		["<leader>9"] = { "9gt", desc = "Goto tab 9" },
		["<leader>b"] = {
			n = { ":bnext<cr>", "Goto Buffer Next" },
			p = { ":bprev<cr>", "Goto Buffer Prev" },
		},
		["<leader>E"] = {
			name = "Edit",
			e = { ':edit <C-r>=expand("%:p:h")<cr>/', "here", silent = false },
			v = { ':vnew <C-r>=expand("%:p:h")<cr>/', "in vsplit", silent = false },
			t = { ':tabedit <C-r>=expand("%:p:h")<cr>/', "in new tab", silent = false },
		},
		["<leader>fn"] = false,
	},
	v = {
		p = {
			[[ 'pgv"'.v:register.'y' ]],
			expr = true,
			noremap = true,
			silent = false,
			desc = "Don't Copy when pasting in visual mode",
		},
		c = { '"_c' },
		J = { ":m '>+1<CR>gv=gv", desc = "Move Line Down" },
		K = { ":m '<-2<CR>gv=gv", desc = "Move Line Up" },
		["<"] = { "<gv" },
		[">"] = { ">gv" },
	},
	o = {
		["ie"] = { ':exec "normal! ggVG"<cr>', desc = "New operator for entire file" },
		["iv"] = { ':exec "normal! HVL"<cr>', desc = "New operator for entire file" },
	},
	t = {
		["<C-l>"] = false,
		["<C-k>"] = false,
	},
	i = {
		[","] = { ",<C-g>u" },
		["."] = { ".<C-g>u" },
		["?"] = { "?<C-g>u" },
		-- ['<C-\\>'] = { '<Esc><Cmd>exe v:count1 . "ToggleTerm"<CR>', desc = 'Open terminal' },
	},
}
